### PR TITLE
Add support for Python 3.11, require NumPy 1.23+

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

Contributes to https://github.com/rapidsai/build-planning/issues/3

This PR adds support for Python 3.11.

It also bumps uses of `NumPy` to `numpy>=1.23`, see https://github.com/rapidsai/build-planning/issues/3#issuecomment-1967952280.

## Notes for Reviewers

This is part of ongoing work to add Python 3.11 support across RAPIDS.

The Python 3.11 CI workflows introduced in https://github.com/rapidsai/shared-workflows/pull/176 are *optional*... they are not yet required to run successfully for PRs to be merged.

This PR can be merged once all jobs are running successfully (including the non-required jobs for Python 3.11). The CI logs should be verified that the jobs are building and testing with Python 3.11.

See https://github.com/rapidsai/shared-workflows/pull/176 for more details.

### CODE REVIEW

**Review by pentschev — APPROVED** [review]

**Review by AyodeAwe — APPROVED** [review]

**Comment by jakirkham** [comment]
Since Python 3.11 requires NumPy 1.23 at a minimum ( https://github.com/rapidsai/cucim/pull/704#issuecomment-1967552641 ), should we update lines like these?

https://github.com/rapidsai/ucxx/blob/e2144cea714d8e21d05b23d85ba8fa9b4ad85c27/conda/recipes/ucxx/meta.yaml#L227

https://github.com/rapidsai/ucxx/blob/e2144cea714d8e21d05b23d85ba8fa9b4ad85c27/dependencies.yaml#L224

**Comment by bdice** [comment]
I noticed Python 3.11 tests were failing. This repo is a little different than other RAPIDS repos, because it builds for each Python version using a matrix in conda-build. I added the missing entry in aadafbe.

**Comment by jakirkham** [comment]
Maybe we need an "add new Python version" script for projects

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
