### PR TITLE
Refactor CI port retry logic for C++ and retry examples

### PR DESCRIPTION
**Pull request by pentschev**
Refactor the CI port retry logic for C++ processes that bind to a specific port so that the code is reused for both benchmarks and examples, and enable examples as those were not covered by the retry logic.

### CODE REVIEW

**Review by wence- — APPROVED** [review]
Minor suggestions to remove some repetition, looks good!

**Comment by pentschev** [comment]
> Minor suggestions to remove some repetition, looks good!

I can't recall details anymore, but I remember seeing some weird issues when expanding variables to execute them  (maybe how bash expands arguments within `""`), this is why I wasn't doing that. But let's see if it will pass like this now or something will go wrong.

**Comment by wence-** [comment]
> > Minor suggestions to remove some repetition, looks good!
> 
> I can't recall details anymore, but I remember seeing some weird issues when expanding variables to execute them (maybe how bash expands arguments within `""`), this is why I wasn't doing that. But let's see if it will pass like this now or something will go wrong.

Seems like no, sorry! https://github.com/rapidsai/ucxx/actions/runs/6337172491/job/17212036065?pr=85#step:7:443

**Comment by wence-** [comment]
And this looks odd https://github.com/rapidsai/ucxx/actions/runs/6337172491/job/17212037078?pr=85#step:7:1027

**Comment by pentschev** [comment]
> Seems like no, sorry! https://github.com/rapidsai/ucxx/actions/runs/6337172491/job/17212036065?pr=85#step:7:443

This one in particular seems to be bash doesn't allow expanding variables as the command line, I [fixed that](https://github.com/rapidsai/ucxx/pull/85/commits/2b611cba59eff6d256d19700a20bf8e6a099fc74) and maybe it will pass. Let's see if there will be other issues besides this.

> And this looks odd https://github.com/rapidsai/ucxx/actions/runs/6337172491/job/17212037078?pr=85#step:7:1027

This is the same issue that has been plaguing CI for a month or two. It can only be reproduced in CentOS 7 (I didn't see a single instace of that elsewhere), I'm suspicious it could be either an old compiler or stdlib bug, but how does one prove that?!

**Comment by pentschev** [comment]
> > And this looks odd https://github.com/rapidsai/ucxx/actions/runs/6337172491/job/17212037078?pr=85#step:7:1027
> 
> This is the same issue that has been plaguing CI for a month or two. It can only be reproduced in CentOS 7 (I didn't see a single instace of that elsewhere), I'm suspicious it could be either an old compiler or stdlib bug, but how does one prove that?!

Also, this seems to have intensified this week for some reason, https://github.com/rapidsai/ucxx/actions/runs/6316749172/job/17185069857 required 9 attempts to pass (versus a common 1-3 in worst cases).

**Review by raydouglass — APPROVED** [review]

**Comment by pentschev** [comment]
Thanks @wence- and @raydouglass !

**Pull request merged**
