### PR TITLE
Fix license name in libucxx wheel

### PR DESCRIPTION
**Pull request by raydouglass**
Updates the license name in `libucxx` to match the actual license

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Review by pentschev — APPROVED** [review]
Thanks @raydouglass !

**Comment by raydouglass** [comment]
@pentschev I doubt the test failures are related to this change, but they are consistent it seems. Are you okay with an admin merge for this or do you need to do any further investigation?

**Comment by pentschev** [comment]
@raydouglass sorry I missed your comment earlier, admin merge is fine. Thanks!

**Comment by pentschev** [comment]
Everything passed this time, but I think we still need approvals maybe from @msarahan ? Or admin merge.

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
> Everything passed this time, but I think we still need approvals maybe from @msarahan ? Or admin merge.

Weird. My approval should have counted here.

**Pull request merged**
