### PR TITLE
Add `ucx` version specifier

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR adds a version specifier for `ucx`.

This particular version specifier will ensure that `ucx` packages from the `rapidsaiai` and `rapidsai-nightly` channels are not used.

Instead, the `ucx` packages from `conda-forge` will be used.

See the links below for details on the versions that exist in each organization:

- https://anaconda.org/rapidsai-nightly/ucx/files
- https://anaconda.org/rapidsai/ucx/files
- https://anaconda.org/conda-forge/ucx/files

### CODE REVIEW

**Review by pentschev — APPROVED** [review]
Thanks @ajschmidt8 !

**Review by jjacobelli — APPROVED** [review]

**Comment by pentschev** [comment]
Thanks @jjacobelli ! You read my mind, was just typing to request an approval! 😄

**Pull request merged**
