### PR TITLE
Raise Python errors when transferring if CUDA not available

### PR DESCRIPTION
**Pull request by pentschev**
Expose whether `ucxx::Context` has CUDA support enable and raise Python errors if attempting to transfer CUDA buffers when that isn't available.

### CODE REVIEW

**Review by wence- — COMMENTED** [review]
Looks good with one minor query about readability in the constructor.

**Comment by pentschev** [comment]
Any other comments here @wence- ? If not, could you approve?

**Review by wence- — APPROVED** [review]
Thanks @pentschev, sorry for the slow review...

**Comment by pentschev** [comment]
No worries @wence- thanks for looking at it and approving. I've resolved the conflict now and will merge it when tests pass.

**Pull request merged**
